# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5b9279a07f5c1ea2c41a5fba97dc8d3"
name = "checkout-product-discounts"
handle = "checkout-product-discounts"
application_url = "https://naples-howto-nuke-diy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dawn-customized-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://naples-howto-nuke-diy.trycloudflare.com/auth/callback",
  "https://naples-howto-nuke-diy.trycloudflare.com/auth/shopify/callback",
  "https://naples-howto-nuke-diy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
